#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgweather
Version  : 3.28.1
Release  : 10
URL      : https://download.gnome.org/sources/libgweather/3.28/libgweather-3.28.1.tar.xz
Source0  : https://download.gnome.org/sources/libgweather/3.28/libgweather-3.28.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: libgweather-data
Requires: libgweather-lib
Requires: libgweather-locales
BuildRequires : glibc-bin
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(geocode-glib-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3
BuildRequires : tzdata

%description
[![Build Status](https://gitlab.gnome.org/GNOME/libgweather/badges/master/build.svg)](https://gitlab.gnome.org/GNOME/libgweather/pipelines)

%package data
Summary: data components for the libgweather package.
Group: Data

%description data
data components for the libgweather package.


%package dev
Summary: dev components for the libgweather package.
Group: Development
Requires: libgweather-lib
Requires: libgweather-data
Provides: libgweather-devel

%description dev
dev components for the libgweather package.


%package lib
Summary: lib components for the libgweather package.
Group: Libraries
Requires: libgweather-data

%description lib
lib components for the libgweather package.


%package locales
Summary: locales components for the libgweather package.
Group: Default

%description locales
locales components for the libgweather package.


%prep
%setup -q -n libgweather-3.28.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522183258
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain  builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libgweather-3.0
%find_lang libgweather-locations

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GWeather-3.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.GWeather.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.GWeather.gschema.xml
/usr/share/libgweather/Locations.xml
/usr/share/libgweather/locations.dtd

%files dev
%defattr(-,root,root,-)
/usr/include/libgweather-3.0/libgweather/gweather-enum-types.h
/usr/include/libgweather-3.0/libgweather/gweather-enums.h
/usr/include/libgweather-3.0/libgweather/gweather-location-entry.h
/usr/include/libgweather-3.0/libgweather/gweather-location.h
/usr/include/libgweather-3.0/libgweather/gweather-timezone-menu.h
/usr/include/libgweather-3.0/libgweather/gweather-timezone.h
/usr/include/libgweather-3.0/libgweather/gweather-version.h
/usr/include/libgweather-3.0/libgweather/gweather-weather.h
/usr/include/libgweather-3.0/libgweather/gweather.h
/usr/lib64/libgweather-3.so
/usr/lib64/pkgconfig/gweather-3.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgweather-3.so.15
/usr/lib64/libgweather-3.so.15.0.0

%files locales -f libgweather-3.0.lang -f libgweather-locations.lang
%defattr(-,root,root,-)

